export const CHAMPION_LIST_REQUEST='CHAMPION_LIST_REQUEST'
export const CHAMPION_LIST_SUCCESS='CHAMPION_LIST_SUCCESS'
export const CHAMPION_LIST_FAIL='CHAMPION_LIST_FAIL'

export const SKIN_LIST_REQUEST='SKIN_LIST_REQUEST'
export const SKIN_LIST_SUCCESS='SKIN_LIST_SUCCESS'
export const SKIN_LIST_FAIL='SKIN_LIST_FAIL'

export const RANK_LIST_REQUEST='RANK_LIST_REQUEST'
export const RANK_LIST_SUCCESS='RANK_LIST_SUCCESS'
export const RANK_LIST_FAIL='RANK_LIST_FAIL'

export const ICON_LIST_REQUEST='ICON_LIST_REQUEST'
export const ICON_LIST_SUCCESS='ICON_LIST_SUCCESS'
export const ICON_LIST_FAIL='ICON_LIST_FAIL'

export const RUNE_LIST_REQUEST='RUNE_LIST_REQUEST'
export const RUNE_LIST_SUCCESS='RUNE_LIST_SUCCESS'
export const RUNE_LIST_FAIL='RUNE_LIST_FAIL'

export const SECRUNE_LIST_REQUEST='SECRUNE_LIST_REQUEST'
export const SECRUNE_LIST_SUCCESS='SECRUNE_LIST_SUCCESS'
export const SECRUNE_LIST_FAIL='SECRUNE_LIST_FAIL'

export const SUMS_LIST_REQUEST='SUMS_LIST_REQUEST'
export const SUMS_LIST_SUCCESS='SUMS_LIST_SUCCESS'
export const SUMS_LIST_FAIL='SUMS_LIST_FAIL'



//users

export const USER_LOGIN_REQUEST='USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS='USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL='USER_LOGIN_FAIL'
export const USER_LOGOUT='USER_LOGOUT'

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";
export const USER_REGISTER_RESET = "USER_REGISTER_RESET";

export const CART_REQUEST = "CART_REQUEST";
export const CART_SUCCESS = "CART_SUCCESS";
export const CART_FAIL = "CART_FAIL";

export const ORDER_CREATE_REQUEST = "ORDER_CREATE_REQUEST";
export const ORDER_CREATE_SUCCESS = "ORDER_CREATE_SUCCESS";
export const ORDER_CREATE_FAIL = "ORDER_CREATE_FAIL";
export const ORDER_CREATE_RESET = "ORDER_CREATE_RESET";


export const ORDER_LIST_REQUEST = "ORDER_LIST_REQUEST";
export const ORDER_LIST_SUCCESS = "ORDER_LIST_SUCCESS";
export const ORDER_LIST_FAIL = "ORDER_LIST_FAIL";
