# Generated by Django 5.1.4 on 2024-12-10 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='champions/')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('history', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='icons/')),
                ('category', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='ranks/')),
            ],
        ),
        migrations.CreateModel(
            name='Rune',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='runes/')),
            ],
        ),
        migrations.CreateModel(
            name='SecRune',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='sec_runes/')),
            ],
        ),
        migrations.CreateModel(
            name='Summoner',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='summoners/')),
            ],
        ),
        migrations.CreateModel(
            name='Skin',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('border', models.BooleanField()),
                ('image', models.ImageField(upload_to='skins/')),
                ('champion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skins', to='base.champion')),
            ],
        ),
        migrations.CreateModel(
            name='Painting',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('price', models.BigIntegerField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('size', models.CharField(choices=[('20x35', '20x35'), ('34x58', '34x58')], max_length=10)),
                ('champion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paintings', to='base.champion')),
                ('icon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paintings', to='base.icon')),
                ('rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paintings', to='base.rank')),
                ('rune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paintings', to='base.rune')),
                ('sec_rune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paintings', to='base.secrune')),
                ('skin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paintings', to='base.skin')),
                ('summoner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paintings', to='base.summoner')),
            ],
        ),
    ]
