# Generated by Django 5.0.6 on 2024-12-30 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_client_email_remove_client_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='history',
        ),
    ]
