# Generated by Django 5.0.6 on 2024-12-30 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_client_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='city',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='full_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='zip',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('price', models.BigIntegerField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('size', models.CharField(choices=[('16x28', '16x28'), ('20x35', '20x35')], max_length=10)),
                ('payment_method', models.CharField(max_length=255)),
                ('payment', models.ImageField(upload_to='payment/')),
                ('icon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paintings', to='base.icon')),
                ('rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paintings', to='base.rank')),
                ('rune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paintings', to='base.rune')),
                ('sec_rune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paintings', to='base.secrune')),
                ('skin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paintings', to='base.skin')),
                ('sum1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paintings1', to='base.summoner')),
                ('sum2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paintings', to='base.summoner')),
            ],
        ),
        migrations.DeleteModel(
            name='Painting',
        ),
    ]
