# Generated by Django 5.0.6 on 2025-01-01 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_order_price_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('under_review', 'Under Review'), ('in_process', 'In Process'), ('shipping', 'Shipping'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='under_review', max_length=20),
        ),
    ]
